export const phoneCountryCodes = [
  { code: 'FR', name: 'France', dialCode: '+33' },
  { code: 'US', name: 'États-Unis', dialCode: '+1' },
  { code: 'CA', name: 'Canada', dialCode: '+1' },
  { code: 'GB', name: 'Royaume-Uni', dialCode: '+44' },
  { code: 'DE', name: 'Allemagne', dialCode: '+49' },
  { code: 'IT', name: 'Italie', dialCode: '+39' },
  { code: 'ES', name: 'Espagne', dialCode: '+34' },
  { code: 'BE', name: 'Belgique', dialCode: '+32' },
  { code: 'CH', name: 'Suisse', dialCode: '+41' },
  { code: 'NL', name: 'Pays-Bas', dialCode: '+31' },
  { code: 'PT', name: 'Portugal', dialCode: '+351' },
  { code: 'AT', name: 'Autriche', dialCode: '+43' },
  { code: 'GR', name: 'Grèce', dialCode: '+30' },
  { code: 'SE', name: 'Suède', dialCode: '+46' },
  { code: 'NO', name: 'Norvège', dialCode: '+47' },
  { code: 'DK', name: 'Danemark', dialCode: '+45' },
  { code: 'FI', name: 'Finlande', dialCode: '+358' },
  { code: 'PL', name: 'Pologne', dialCode: '+48' },
  { code: 'CZ', name: 'République tchèque', dialCode: '+420' },
  { code: 'RO', name: 'Roumanie', dialCode: '+40' },
  { code: 'HU', name: 'Hongrie', dialCode: '+36' },
  { code: 'IE', name: 'Irlande', dialCode: '+353' },
  { code: 'MA', name: 'Maroc', dialCode: '+212' },
  { code: 'DZ', name: 'Algérie', dialCode: '+213' },
  { code: 'TN', name: 'Tunisie', dialCode: '+216' },
  { code: 'SN', name: 'Sénégal', dialCode: '+221' },
  { code: 'CI', name: 'Côte d\'Ivoire', dialCode: '+225' },
  { code: 'CM', name: 'Cameroun', dialCode: '+237' },
  { code: 'CD', name: 'République démocratique du Congo', dialCode: '+243' },
  { code: 'ZA', name: 'Afrique du Sud', dialCode: '+27' },
  { code: 'EG', name: 'Égypte', dialCode: '+20' },
  { code: 'CN', name: 'Chine', dialCode: '+86' },
  { code: 'JP', name: 'Japon', dialCode: '+81' },
  { code: 'IN', name: 'Inde', dialCode: '+91' },
  { code: 'KR', name: 'Corée du Sud', dialCode: '+82' },
  { code: 'AU', name: 'Australie', dialCode: '+61' },
  { code: 'NZ', name: 'Nouvelle-Zélande', dialCode: '+64' },
  { code: 'BR', name: 'Brésil', dialCode: '+55' },
  { code: 'MX', name: 'Mexique', dialCode: '+52' },
  { code: 'AR', name: 'Argentine', dialCode: '+54' },
  { code: 'CL', name: 'Chili', dialCode: '+56' },
  { code: 'CO', name: 'Colombie', dialCode: '+57' },
  { code: 'PE', name: 'Pérou', dialCode: '+51' },
  { code: 'RU', name: 'Russie', dialCode: '+7' },
  { code: 'TR', name: 'Turquie', dialCode: '+90' },
  { code: 'SA', name: 'Arabie saoudite', dialCode: '+966' },
  { code: 'AE', name: 'Émirats arabes unis', dialCode: '+971' },
  { code: 'IL', name: 'Israël', dialCode: '+972' },
  { code: 'TH', name: 'Thaïlande', dialCode: '+66' },
  { code: 'VN', name: 'Viêt Nam', dialCode: '+84' },
  { code: 'ID', name: 'Indonésie', dialCode: '+62' },
  { code: 'MY', name: 'Malaisie', dialCode: '+60' },
  { code: 'SG', name: 'Singapour', dialCode: '+65' },
  { code: 'PH', name: 'Philippines', dialCode: '+63' }
].sort((a, b) => a.name.localeCompare(b.name));
