export const PLAYLISTS = [
  {
    key: "favorites",
    title: "Mes favoris",
    icon: "pi pi-heart-fill",
    description: "Vidéos que vous avez ajoutées à vos favoris",
    borderClass: "border-green-500/40",
    accentClass: "text-green-300",
    accentBarClass: "bg-green-500/60",
    glowClass: "shadow-green-500/20",
    hoverClass: "hover:border-green-700/70 hover:bg-green-500/10",
  },
  {
    key: "watch_later",
    title: "À voir plus tard",
    icon: "pi pi-clock",
    description: "Vidéos sauvegardées pour visionner plus tard",
    borderClass: "border-blue-500/40",
    accentClass: "text-blue-300",
    accentBarClass: "bg-blue-500/60",
    glowClass: "shadow-blue-500/20",
    hoverClass: "hover:border-blue-700/70 hover:bg-blue-500/10",

  },
  {
    key: "report",
    title: "Vidéos signalées",
    icon: "pi pi-flag",
    description: "Contenus que vous avez signalés",
    borderClass: "border-red-500/40",
    accentClass: "text-red-300",
    accentBarClass: "bg-red-500/60",
    glowClass: "shadow-red-500/20",
    hoverClass: "hover:border-red-700/70 hover:bg-red-500/10",
  },
];
